services:
  xtts_server:
    container_name: xtts_server
    image: ghcr.io/coqui-ai/xtts-streaming-server:latest-cpu
    environment:
      - COQUI_TOS_AGREED=1
    ports:
      - "8820:80"

  python_app:
    container_name: python_app
    build:
      context: .
    volumes:
      - ./:/app
    depends_on:
      - xtts_server
    # command: python demo.py
    tty: true
    ports:
      - "3009:3009"
  
